### PR TITLE
Update to Bevy 0.11

### PR DESCRIPTION
**Pull request by anellie**
This updates all bevy dependencies to 0.11 and fixes any compile errors that occurred in the adapter.
Most changes were very minor; the new schedule API and `Event` derives were probably the biggest change.
Thank you for naia! I'm looking forward to use it in an upcoming project. I hope this PR proves useful.

### CODE REVIEW

**Comment by connorcarpenter** [comment]
Wow this is wonderful, thank you :)

**Comment by connorcarpenter** [comment]
This is great! Thank you so much! :) Will merge soon

**Comment by anellie** [comment]
I'm glad I could help! Thank you as well :)

**Comment by anellie** [comment]
Just realized this breaks the demo, oops! Will fix that and add it to the PR real quick

**Comment by anellie** [comment]
Demo is working again, luckily didn't require many changes either!

**Comment by NoFr1ends** [comment]
Any update on when this will get merged?

**Comment by connorcarpenter** [comment]
Thank you for your patience! This has been merged into Release 0.21.1

**Pull request closed without merging**
